MANUAL_NAME_MAP = {
    'Frederick P. Whiddon College of Medicine at the University of South Alabama': 'University of  South Alabama College of Medicine',
    'University of Alabama at Birmingham Marnix E. Heersink School of Medicine': 'University of  Alabama School of Medicine',
    'University of Arizona College of Medicine': 'University of  Arizona College of Medicine - Tucson',
    'University of Arizona College of Medicine - Phoenix': 'University of  Arizona School of Medicine - Phoenix',
    'University of Arkansas for Medical Sciences College of Medicine': 'University of Arkansas for Medical Sciences College of Medicine',
    'California Northstate University College of Medicine': 'California Northstate University College of Medicine',
    'California University of Science and Medicine-School of Medicine': 'California University of Science and Medicine',
    'Kaiser Permanente Bernard J. Tyson School of Medicine': 'Kaiser Permanente School of  Medicine',
    'Keck School of Medicine of the University of Southern California': 'University of Southern California Keck School of Medicine',
    'Loma Linda University School of Medicine': 'Loma Linda University School of Medicine',
    'Stanford University School of Medicine': 'Stanford University  School of Medicine',
    'University of California, Davis, School of Medicine': 'University of California – Davis School of Medicine',
    'University of California, Irvine, School of Medicine': 'University  of California – Irvine School of Medicine',
    'University of California, Los Angeles David Geffen School of Medicine': 'University of California –  Los Angeles David Geffen School of Medicine',
    'University of California, Riverside School of Medicine': 'University of California – Riverside School of Medicine',
    'University of California, San Diego School of Medicine': 'University of California – San Diego School of Medicine',
    'University of California, San Francisco, School of Medicine': 'University of  California – San Francisco School of Medicine',
    'University of Colorado School of Medicine': 'University of Colorado School of Medicine',
    'Frank H. Netter MD School of Medicine at Quinnipiac University': 'Quinnipiac  University Frank H. Netter MD School of Medicine',
    'University of Connecticut School of Medicine': 'University of  Connecticut School of Medicine',
    'Yale School of Medicine': 'Yale School of  Medicine',
    'George Washington University School of Medicine & Health Sciences': 'George Washington University School of Medicine and Health Sciences',
    'Georgetown University School of Medicine': 'Georgetown University School of Medicine',
    'Howard University College of Medicine': 'Howard University College of Medicine',
    'Charles E. Schmidt College of Medicine at Florida Atlantic University': 'Florida Atlantic  University Charles E. Schmidt College of Medicine',
    'Florida International University Herbert Wertheim College of Medicine': 'Florida International University Herbert Wertheim College of  Medicine',
    'Florida State University College of Medicine': 'Florida State University College  of Medicine',
    'Nova Southeastern University Dr. Kiran C. Patel College of Allopathic Medicine': 'Nova  Southeastern University Dr. Kiran C. Patel College of Allopathic Medicine',
    'USF Health Morsani College of Medicine': 'University of South Florida Health Morsani College of Medicine',
    'University of Central Florida College of Medicine': 'University of Central Florida College of Medicine',
    'University of Florida College of Medicine': 'University of Florida College of  Medicine',
    'University of Miami Leonard M. Miller School of Medicine': 'University of Miami Miller School of Medicine',
    'Emory University School of Medicine': 'Emory  University School of Medicine',
    'Medical College of Georgia at Augusta University': 'Medical College of Georgia at Augusta University',
    'Mercer University School of Medicine': 'Mercer  University School of Medicine',
    'Morehouse School of Medicine': 'Morehouse  School of Medicine',
    'University of Hawaii, John A. Burns School of Medicine': 'University of Hawaii John A. Burns School of Medicine',
    'Carle Illinois College of Medicine': 'Carle Illinois College of  Medicine',
    'Chicago Medical School at Rosalind Franklin University of Medicine & Science': 'Chicago Medical School at Rosalind Franklin University of Medicine and  Science',
    'Loyola University Chicago Stritch School of Medicine': 'Loyola  University of Chicago Stritch School of Medicine',
    'Northwestern University The Feinberg School of Medicine': 'Northwestern  University The Feinberg School of Medicine',
    'Rush Medical College of Rush University Medical Center': 'Rush Medical College of Rush University',
    'Southern Illinois University School of Medicine': 'Southern  Illinois University School of Medicine',
    'University of Chicago Division of the Biological Sciences The Pritzker School of Medicine': 'University of  Chicago Pritzker School of Medicine',
    'University of Illinois College of Medicine': 'University of  Illinois College of Medicine',
    'Indiana University School of Medicine': 'Indiana University  School of Medicine',
    'University of Iowa Roy J. and Lucille A. Carver College of Medicine': 'University of Iowa Carver College of Medicine',
    'University of Kansas School of Medicine': 'University of Kansas School of Medicine',
    'University of Kentucky College of Medicine': 'University  of Kentucky College of Medicine',
    'University of Louisville School of Medicine': 'University of Louisville School of Medicine',
    'Louisiana State University School of Medicine in New Orleans': 'Louisiana  State University – New Orleans School of Medicine',
    'Louisiana State University School of Medicine in Shreveport': 'Louisiana State University – Shreveport School of Medicine',
    'Tulane University School of Medicine': 'Tulane University  School of Medicine',
    'Johns Hopkins University School of Medicine': 'Johns Hopkins University School of Medicine',
    'Uniformed Services University of the Health Sciences F. Edward Hebert School of Medicine': 'Uniformed Services University of the Health Sciences F. Edward Hebert School  of Medicine',
    'University of Maryland School of Medicine': 'University of  Maryland School of Medicine',
    'Boston University Aram V. Chobanian & Edward Avedisian School of Medicine': 'Boston University School of Medicine',
    'Harvard Medical School': 'Harvard Medical  School',
    'Tufts University School of Medicine': 'Tufts University School of Medicine',
    'University of Massachusetts T.H. Chan School of Medicine': 'University of Massachusetts Medical School',
    'Covenant HealthCare College of Medicine at Central Michigan University': 'Central Michigan University College of Medicine',
    'Michigan State University College of Human Medicine': 'Michigan State University College of  Human Medicine',
    'Oakland University William Beaumont School of Medicine': 'Oakland  University William Beaumont School of Medicine',
    'University of Michigan Medical School': 'University of Michigan Medical School',
    'Wayne State University School of Medicine': 'Wayne  State University School of Medicine',
    'Western Michigan University Homer Stryker M.D. School of Medicine': 'Western Michigan University School of  Medicine',
    'Mayo Clinic Alix School of Medicine': 'Mayo Clinic Alix School of Medicine',
    'University of Mississippi School of Medicine': 'University of Mississippi School of Medicine',
    'Saint Louis University School of Medicine': 'Saint Louis University School of Medicine',
    'University of Missouri-Columbia School of Medicine': 'University of Missouri – Columbia School of Medicine',
    'University of Missouri-Kansas City School of Medicine': 'University of Missouri – Kansas  City School of Medicine',
    'Washington University in St. Louis School of Medicine': 'Washington University School of  Medicine',
    'Creighton University School of Medicine': 'Creighton University School of Medicine',
    'University of Nebraska College of Medicine': 'University of Nebraska Medical Center College of Medicine',
    'Kirk Kerkorian School of Medicine at UNLV': 'University of Nevada Las Vegas School of  Medicine',
    'University of Nevada, Reno School of Medicine': 'University of Nevada Reno School of  Medicine',
    'Geisel School of Medicine at Dartmouth': 'Geisel School  of Medicine at Dartmouth',
    'Cooper Medical School of Rowan University': 'Cooper Medical School of  Rowan University',
    'Hackensack Meridian School of Medicine': 'Hackensack Meridian School of Medicine',
    'Rutgers New Jersey Medical School': 'Rutgers New Jersey Medical  School',
    'Rutgers, Robert Wood Johnson Medical School': 'Rutgers Robert Wood Johnson Medical School',
    'University of New Mexico School of Medicine': 'University of New Mexico School of Medicine',
    'Albany Medical College': 'Albany  Medical College',
    'Albert Einstein College of Medicine': 'Albert  Einstein College of Medicine',
    'Columbia University Vagelos College of Physicians and Surgeons': 'Columbia University College of Physicians and Surgeons',
    'Donald and Barbara Zucker School of Medicine at Hofstra/Northwell': 'Hofstra  Northwell School of Medicine',
    'Icahn School of Medicine at Mount Sinai': 'Icahn School of Medicine at Mount  Sinai',
    'Jacobs School of Medicine and Biomedical Sciences at the University at Buffalo': 'University at Buffalo  Jacobs School of Medicine and Biomedical Sciences',
    'NYU Grossman Long Island School of Medicine': 'New York  University Long Island School of Medicine',
    'NYU Grossman School of Medicine': 'New York  University Grossman School of Medicine',
    'New York Medical College': 'New York Medical College',
    'Renaissance School of Medicine at Stony Brook University': 'Stony Brook  University School of Medicine',
    'SUNY Downstate Health Sciences University College of Medicine': 'SUNY – Downstate  Medical Center College of Medicine',
    'State University of New York Upstate Medical University Alan and Marlene Norton College of Medicine': 'SUNY – Upstate Medical  University',
    'University of Rochester School of Medicine and Dentistry': 'University of Rochester School of Medicine and Dentistry',
    'Weill Cornell Medicine': 'Weill Cornell Medical College',
    'Brody School of Medicine at East Carolina University': 'East  Carolina University Brody School of Medicine',
    'Duke University School of Medicine': 'Duke University School of Medicine',
    'University of North Carolina at Chapel Hill School of Medicine': 'University of North Carolina at  Chapel Hill School of Medicine',
    'Wake Forest University School of Medicine': 'Wake Forest School of Medicine',
    'University of North Dakota School of Medicine and Health Sciences': 'University of  North Dakota School of Medicine and Health Sciences',
    'Case Western Reserve University School of Medicine': 'Case Western Reserve University School of Medicine',
    'Northeast Ohio Medical University': 'Northeast Ohio Medical University',
    'Ohio State University College of Medicine': 'The Ohio State University College of Medicine',
    'The University of Toledo College of Medicine and Life Sciences': 'The University of  Toledo College of Medicine and Life Sciences',
    'University of Cincinnati College of Medicine': 'University of Cincinnati  College of Medicine',
    'Wright State University Boonshoft School of Medicine': 'Wright State  University Boonshoft School of Medicine',
    'University of Oklahoma College of Medicine': 'University of Oklahoma College of Medicine',
    'Oregon Health & Science University School of Medicine': 'Oregon  Health & Science University School of Medicine',
    'Drexel University College of Medicine': 'Drexel University College of Medicine',
    'Geisinger Commonwealth School of Medicine': 'Geisinger Commonwealth School of Medicine',
    'Lewis Katz School of Medicine at Temple University': 'Temple University Lewis Katz  School of Medicine',
    'Pennsylvania State University College of Medicine': 'Pennsylvania State University  College of Medicine',
    'Perelman School of Medicine at the University of Pennsylvania': 'Perelman School of Medicine University of Pennsylvania',
    'Sidney Kimmel Medical College at Thomas Jefferson University': 'Sidney Kimmel Medical College at Thomas Jefferson University',
    'University of Pittsburgh School of Medicine': 'University of Pittsburgh School of Medicine',
    'Ponce Health Sciences University School of Medicine': 'Ponce School of  Medicine and Health Sciences',
    'San Juan Bautista School of Medicine': 'San  Juan Bautista School of Medicine',
    'Universidad Central del Caribe School of Medicine': 'Universidad Central Del Caribe  School of Medicine',
    'University of Puerto Rico School of Medicine': 'University of Puerto Rico School of  Medicine',
    'The Warren Alpert Medical School of Brown University': 'Brown  University The Warren Alpert Medical School',
    'Medical University of South Carolina College of Medicine': 'Medical University of South Carolina College of Medicine',
    'University of South Carolina Kay and C. Edward Floyd, M.D. School of Medicine': 'University of  South Carolina School of Medicine – Columbia',
    'University of South Carolina School of Medicine Greenville': 'University of South Carolina School of Medicine – Greenville',
    'University of South Dakota, Sanford School of Medicine': 'University of South Dakota Sanford School of Medicine',
    'East Tennessee State University James H. Quillen College of Medicine': 'East  Tennessee State University Quillen College of Medicine',
    'Meharry Medical College': 'Meharry Medical  College School of Medicine',
    'University of Tennessee Health Science Center College of Medicine': 'University  of Tennessee Health Science Center College of Medicine',
    'Vanderbilt University School of Medicine': 'Vanderbilt University School of Medicine',
    'Anne Burnett Marion School of Medicine at Texas Christian University': 'TCU and UNTHSC  School of Medicine',
    'Spencer Fox Eccles School of Medicine at the University of Utah': 'University  of Utah School of Medicine',
    'Robert Larner, M.D., College of Medicine at the University of Vermont': 'The  University of Vermont Larner College of Medicine',
    'Eastern Virginia Medical School at Old Dominion University': 'Eastern Virginia Medical School',
    'University of Virginia School of Medicine': 'University of  Virginia School of Medicine',
    'Virginia Commonwealth University School of Medicine': 'Virginia  Commonwealth University School of Medicine',
    'Virginia Tech Carilion School of Medicine': 'Virginia  Tech Carilion School of Medicine and Research Institute',
    'University of Washington School of Medicine': 'University of  Washington School of Medicine',
    'Washington State University Elson S. Floyd College of Medicine': 'Washington State University Elson S. Floyd College of Medicine',
    'Marshall University Joan C. Edwards School of Medicine': 'Marshall University Joan C. Edwards School of Medicine',
    'West Virginia University School of Medicine': 'West  Virginia University School of Medicine',
    'Medical College of Wisconsin': 'Medical College of Wisconsin',
    'University of Wisconsin School of Medicine and Public Health': 'University of Wisconsin School of Medicine and Public Health',
}
